# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
 :openvpnServerOffice1 => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.0.2', adapter: 2, netmask: "255.255.255.248", virtualbox__intnet: "internet"},
                   {ip: '192.168.10.1', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "officeSubnet1"} # intnet это vlan
               ]
  },

 :openvpnClientGatewayOffice2 => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.0.3', adapter: 2, netmask: "255.255.255.248", virtualbox__intnet: "internet"},
                   {ip: '192.168.20.1', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "officeSubnet2"}
               ]
  },

  :office1Computer => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.10.2', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "officeSubnet1"}
                ]
  },
  
  :office2Computer => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.20.2', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "officeSubnet2"}
                ]
  }

}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        config.vm.provider "virtualbox" do |v|
          v.memory = 256
        end

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
        # Директивы говорящие что надо использовать вход в гостевые машины используя логин и пароль
        #config.ssh.username = 'vagrant'
        #config.ssh.password = 'vagrant'
        #config.ssh.insert_key = false
        #config.ssh.connect_timeout = 5


        case boxname.to_s
        when "openvpnServerOffice1"
          config.vm.provision "ansible" do |ansible|
          ansible.playbook = "ovpnTUN_1.yml"
        end  
            

          #box.vm.provision "shell", path: "./files/sed.sh"
    
        when "openvpnClientGatewayOffice2"
          config.vm.provision "ansible" do |ansible|
          ansible.playbook = "ovpnTUN_2.yml"
        end  
     
        when "office1Computer"
          config.vm.provision "ansible" do |ansible|
          ansible.playbook = "ovpnTUN_3.yml"
        end  
            # Установка софта; Форвардинг для прохождения транзитного траффика; Установка шлюза на eth1 и удаление на eth0
            sudo yum install -y epel-release; sudo yum install -y tcpdump iperf3 wget nano
            sudo bash -c 'echo "192.168.20.0/24 via 192.168.10.1 dev eth1" >> /etc/sysconfig/network-scripts/route-eth1'
            sudo reboot
            SHELL
        when "office2Computer"
          config.vm.provision "ansible" do |ansible|
          ansible.playbook = "ovpnTUN_3.yml"
        end  
      
    end

  end
  
  
end
